export const SET_COURSES = "SET_COURSES";
export const DELETE_COURSE = "DELETE_COURSE";
export const ADD_COURSE = "ADD_COURSE";
export const FETCH_COURSES = "FETCH_COURSES";
export const UPDATE_COURSE = "UPDATE_COURSE";